<a href="https://colab.research.google.com/github/AaronLin417/Data-Science/blob/master/Homework/02_Linear_algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear algebra with Numpy
https://github.com/drvinceknight/Python-Mathematics-Handbook/blob/ee91644ab2028acb2f4c42839cc335aca20229c5/02-Linear-algebra-with-Numpy.ipynb

#Manipulating matrices

In [0]:
import numpy as np

Defining A&B

In [2]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [3]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [4]:
12*A

matrix([[ 60,  72,  24],
        [ 48,  84, 228],
        [  0,  36, 144]])

In [5]:
A ** 6

matrix([[ 2252617,  7279152, 22659352],
        [ 4189392, 13800421, 43283616],
        [ 1990128,  6624768, 20861445]])

In [6]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [7]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [8]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

In [9]:
#Exercise
A = np.matrix([[1, -1],
               [2, 1]])
A ** 2 - 2 * A + 3

matrix([[0, 3],
        [3, 0]])

#Solving Matrix equations

In [0]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

Using the linalg.solve command

In [11]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

Verifing result

In [12]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

In [13]:
#Exercise
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])
b = np.matrix([[-1], [2], [1]])
x = np.linalg.solve(B, b)
x

matrix([[-0.25892857],
        [ 0.40178571],
        [ 0.28571429]])

#Matrix inversion and determinants

In [14]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

Verifing that A^-1 * A = 1

In [15]:
A * Ainv
#The below might not look like the identity matrix but if you look closer you see that the diagonals are all 1 and the off diagonals are a very small number (which from a computer's point of view is 0).

matrix([[ 1.00000000e+00,  4.99600361e-16, -4.71844785e-16],
        [ 1.38777878e-16,  1.00000000e+00, -2.63677968e-16],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

Calculating the determinant

In [16]:
np.linalg.det(A)

-129.00000000000009

In [17]:
#Exercise
C = np.matrix([[17, -2, 12],
               [4, 3, 7],
               [12, -1, 5]])
Cinv = np.linalg.inv(C)
Cinv

matrix([[-0.09401709,  0.00854701,  0.21367521],
        [-0.27350427,  0.25213675,  0.3034188 ],
        [ 0.17094017,  0.02991453, -0.25213675]])

In [18]:
np.linalg.det(C)

-234.00000000000006